// Granular permissions checked by PermissionsGuard via @RequirePermission().
// Naming convention: RESOURCE_ACTION. See src/auth/constants/role-permissions.ts
// for the role -> permission mapping.
export enum Permission {
  ORG_VIEW = 'ORG_VIEW',
  ORG_UPDATE = 'ORG_UPDATE',
  ORG_DELETE = 'ORG_DELETE',

  MEMBER_VIEW = 'MEMBER_VIEW',
  MEMBER_INVITE = 'MEMBER_INVITE',
  MEMBER_UPDATE = 'MEMBER_UPDATE',
  MEMBER_REMOVE = 'MEMBER_REMOVE',

  PROJECT_VIEW = 'PROJECT_VIEW',
  PROJECT_CREATE = 'PROJECT_CREATE',
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  PROJECT_DELETE = 'PROJECT_DELETE',

  TASK_VIEW = 'TASK_VIEW',
  TASK_CREATE = 'TASK_CREATE',
  TASK_UPDATE = 'TASK_UPDATE',
  TASK_DELETE = 'TASK_DELETE',
  TASK_ASSIGN = 'TASK_ASSIGN',
  TASK_COMMENT = 'TASK_COMMENT',

  TEAM_VIEW = 'TEAM_VIEW',
  TEAM_UPDATE = 'TEAM_UPDATE',

  ANALYTICS_VIEW = 'ANALYTICS_VIEW',
  ACTIVITY_VIEW = 'ACTIVITY_VIEW',

  MESSAGE_VIEW = 'MESSAGE_VIEW',
  MESSAGE_CREATE = 'MESSAGE_CREATE',
  MESSAGE_DELETE = 'MESSAGE_DELETE',

  NOTIFICATION_VIEW = 'NOTIFICATION_VIEW',
  NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE',

  API_KEY_VIEW = 'API_KEY_VIEW',
  API_KEY_CREATE = 'API_KEY_CREATE',
  API_KEY_DELETE = 'API_KEY_DELETE',

  WEBHOOK_VIEW = 'WEBHOOK_VIEW',
  WEBHOOK_CREATE = 'WEBHOOK_CREATE',
  WEBHOOK_UPDATE = 'WEBHOOK_UPDATE',
  WEBHOOK_DELETE = 'WEBHOOK_DELETE',
  WEBHOOK_TEST = 'WEBHOOK_TEST',

  INTEGRATION_VIEW = 'INTEGRATION_VIEW',
  INTEGRATION_CONNECT = 'INTEGRATION_CONNECT',
  INTEGRATION_DISCONNECT = 'INTEGRATION_DISCONNECT',

  BILLING_VIEW = 'BILLING_VIEW',
  BILLING_MANAGE = 'BILLING_MANAGE',

  SETTINGS_VIEW = 'SETTINGS_VIEW',
  SETTINGS_UPDATE = 'SETTINGS_UPDATE',
}
